[package]
name = "spekje"
version = "0.0.0"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
edition = "2018"

[dependencies]
gdk         = "0.11.0"
gdk-pixbuf  = "0.7.0"
gio         = "0.7.0"
glib        = "0.8.1"
gtk         = "0.7.0"
relm        = "0.17.0"
relm-derive = "0.17.0"
